;;;raw-bindings-sdl2 - FFI bindings to SDL2
;;;Written in 2017 by Wilfredo Velázquez-Rodríguez <zulu.inuoe@gmail.com>
;;;
;;;To the extent possible under law, the author(s) have dedicated all copyright
;;;and related and neighboring rights to this software to the public domain
;;;worldwide. This software is distributed without any warranty.
;;;You should have received a copy of the CC0 Public Domain Dedication along
;;;with this software. If not, see
;;;<http://creativecommons.org/publicdomain/zero/1.0/>.

(in-package #:raw-bindings-sdl2)

(defsdl2enum sdl-scancode
  (+sdl-scancode-unknown+ 0)
  (+sdl-scancode-a+ 4)
  (+sdl-scancode-b+ 5)
  (+sdl-scancode-c+ 6)
  (+sdl-scancode-d+ 7)
  (+sdl-scancode-e+ 8)
  (+sdl-scancode-f+ 9)
  (+sdl-scancode-g+ 10)
  (+sdl-scancode-h+ 11)
  (+sdl-scancode-i+ 12)
  (+sdl-scancode-j+ 13)
  (+sdl-scancode-k+ 14)
  (+sdl-scancode-l+ 15)
  (+sdl-scancode-m+ 16)
  (+sdl-scancode-n+ 17)
  (+sdl-scancode-o+ 18)
  (+sdl-scancode-p+ 19)
  (+sdl-scancode-q+ 20)
  (+sdl-scancode-r+ 21)
  (+sdl-scancode-s+ 22)
  (+sdl-scancode-t+ 23)
  (+sdl-scancode-u+ 24)
  (+sdl-scancode-v+ 25)
  (+sdl-scancode-w+ 26)
  (+sdl-scancode-x+ 27)
  (+sdl-scancode-y+ 28)
  (+sdl-scancode-z+ 29)

  (+sdl-scancode-1+ 30)
  (+sdl-scancode-2+ 31)
  (+sdl-scancode-3+ 32)
  (+sdl-scancode-4+ 33)
  (+sdl-scancode-5+ 34)
  (+sdl-scancode-6+ 35)
  (+sdl-scancode-7+ 36)
  (+sdl-scancode-8+ 37)
  (+sdl-scancode-9+ 38)
  (+sdl-scancode-0+ 39)

  (+sdl-scancode-return+ 40)
  (+sdl-scancode-escape+ 41)
  (+sdl-scancode-backspace+ 42)
  (+sdl-scancode-tab+ 43)
  (+sdl-scancode-space+ 44)

  (+sdl-scancode-minus+ 45)
  (+sdl-scancode-equals+ 46)
  (+sdl-scancode-leftbracket+ 47)
  (+sdl-scancode-rightbracket+ 48)
  (+sdl-scancode-backslash+ 49)

  (+sdl-scancode-nonushash+ 50)
  (+sdl-scancode-semicolon+ 51)
  (+sdl-scancode-apostrophe+ 52)
  (+sdl-scancode-grave+ 53)
  (+sdl-scancode-comma+ 54)
  (+sdl-scancode-period+ 55)
  (+sdl-scancode-slash+ 56)

  (+sdl-scancode-capslock+ 57)

  (+sdl-scancode-f1+ 58)
  (+sdl-scancode-f2+ 59)
  (+sdl-scancode-f3+ 60)
  (+sdl-scancode-f4+ 61)
  (+sdl-scancode-f5+ 62)
  (+sdl-scancode-f6+ 63)
  (+sdl-scancode-f7+ 64)
  (+sdl-scancode-f8+ 65)
  (+sdl-scancode-f9+ 66)
  (+sdl-scancode-f10+ 67)
  (+sdl-scancode-f11+ 68)
  (+sdl-scancode-f12+ 69)

  (+sdl-scancode-printscreen+ 70)
  (+sdl-scancode-scrolllock+ 71)
  (+sdl-scancode-pause+ 72)
  (+sdl-scancode-insert+ 73)
  (+sdl-scancode-home+ 74)
  (+sdl-scancode-pageup+ 75)
  (+sdl-scancode-delete+ 76)
  (+sdl-scancode-end+ 77)
  (+sdl-scancode-pagedown+ 78)
  (+sdl-scancode-right+ 79)
  (+sdl-scancode-left+ 80)
  (+sdl-scancode-down+ 81)
  (+sdl-scancode-up+ 82)

  (+sdl-scancode-numlockclear+ 83)
  (+sdl-scancode-kp-divide+ 84)
  (+sdl-scancode-kp-multiply+ 85)
  (+sdl-scancode-kp-minus+ 86)
  (+sdl-scancode-kp-plus+ 87)
  (+sdl-scancode-kp-enter+ 88)
  (+sdl-scancode-kp-1+ 89)
  (+sdl-scancode-kp-2+ 90)
  (+sdl-scancode-kp-3+ 91)
  (+sdl-scancode-kp-4+ 92)
  (+sdl-scancode-kp-5+ 93)
  (+sdl-scancode-kp-6+ 94)
  (+sdl-scancode-kp-7+ 95)
  (+sdl-scancode-kp-8+ 96)
  (+sdl-scancode-kp-9+ 97)
  (+sdl-scancode-kp-0+ 98)
  (+sdl-scancode-kp-period+ 99)

  (+sdl-scancode-nonusbackslash+ 100)
  (+sdl-scancode-application+ 101)
  (+sdl-scancode-power+ 102)
  (+sdl-scancode-kp-equals+ 103)
  (+sdl-scancode-f13+ 104)
  (+sdl-scancode-f14+ 105)
  (+sdl-scancode-f15+ 106)
  (+sdl-scancode-f16+ 107)
  (+sdl-scancode-f17+ 108)
  (+sdl-scancode-f18+ 109)
  (+sdl-scancode-f19+ 110)
  (+sdl-scancode-f20+ 111)
  (+sdl-scancode-f21+ 112)
  (+sdl-scancode-f22+ 113)
  (+sdl-scancode-f23+ 114)
  (+sdl-scancode-f24+ 115)
  (+sdl-scancode-execute+ 116)
  (+sdl-scancode-help+ 117)
  (+sdl-scancode-menu+ 118)
  (+sdl-scancode-select+ 119)
  (+sdl-scancode-stop+ 120)
  (+sdl-scancode-again+ 121)
  (+sdl-scancode-undo+ 122)
  (+sdl-scancode-cut+ 123)
  (+sdl-scancode-copy+ 124)
  (+sdl-scancode-paste+ 125)
  (+sdl-scancode-find+ 126)
  (+sdl-scancode-mute+ 127)
  (+sdl-scancode-volumeup+ 128)
  (+sdl-scancode-volumedown+ 129)

  (+sdl-scancode-kp-comma+ 133)
  (+sdl-scancode-kp-equalsas400+ 134)

  (+sdl-scancode-international1+ 135)
  (+sdl-scancode-international2+ 136)
  (+sdl-scancode-international3+ 137)
  (+sdl-scancode-international4+ 138)
  (+sdl-scancode-international5+ 139)
  (+sdl-scancode-international6+ 140)
  (+sdl-scancode-international7+ 141)
  (+sdl-scancode-international8+ 142)
  (+sdl-scancode-international9+ 143)
  (+sdl-scancode-lang1+ 144)
  (+sdl-scancode-lang2+ 145)
  (+sdl-scancode-lang3+ 146)
  (+sdl-scancode-lang4+ 147)
  (+sdl-scancode-lang5+ 148)
  (+sdl-scancode-lang6+ 149)
  (+sdl-scancode-lang7+ 150)
  (+sdl-scancode-lang8+ 151)
  (+sdl-scancode-lang9+ 152)

  (+sdl-scancode-alterase+ 153)
  (+sdl-scancode-sysreq+ 154)
  (+sdl-scancode-cancel+ 155)
  (+sdl-scancode-clear+ 156)
  (+sdl-scancode-prior+ 157)
  (+sdl-scancode-return2+ 158)
  (+sdl-scancode-separator+ 159)
  (+sdl-scancode-out+ 160)
  (+sdl-scancode-oper+ 161)
  (+sdl-scancode-clearagain+ 162)
  (+sdl-scancode-crsel+ 163)
  (+sdl-scancode-exsel+ 164)

  (+sdl-scancode-kp-00+ 176)
  (+sdl-scancode-kp-000+ 177)
  (+sdl-scancode-thousandsseparator+ 178)
  (+sdl-scancode-decimalseparator+ 179)
  (+sdl-scancode-currencyunit+ 180)
  (+sdl-scancode-currencysubunit+ 181)
  (+sdl-scancode-kp-leftparen+ 182)
  (+sdl-scancode-kp-rightparen+ 183)
  (+sdl-scancode-kp-leftbrace+ 184)
  (+sdl-scancode-kp-rightbrace+ 185)
  (+sdl-scancode-kp-tab+ 186)
  (+sdl-scancode-kp-backspace+ 187)
  (+sdl-scancode-kp-a+ 188)
  (+sdl-scancode-kp-b+ 189)
  (+sdl-scancode-kp-c+ 190)
  (+sdl-scancode-kp-d+ 191)
  (+sdl-scancode-kp-e+ 192)
  (+sdl-scancode-kp-f+ 193)
  (+sdl-scancode-kp-xor+ 194)
  (+sdl-scancode-kp-power+ 195)
  (+sdl-scancode-kp-percent+ 196)
  (+sdl-scancode-kp-less+ 197)
  (+sdl-scancode-kp-greater+ 198)
  (+sdl-scancode-kp-ampersand+ 199)
  (+sdl-scancode-kp-dblampersand+ 200)
  (+sdl-scancode-kp-verticalbar+ 201)
  (+sdl-scancode-kp-dblverticalbar+ 202)
  (+sdl-scancode-kp-colon+ 203)
  (+sdl-scancode-kp-hash+ 204)
  (+sdl-scancode-kp-space+ 205)
  (+sdl-scancode-kp-at+ 206)
  (+sdl-scancode-kp-exclam+ 207)
  (+sdl-scancode-kp-memstore+ 208)
  (+sdl-scancode-kp-memrecall+ 209)
  (+sdl-scancode-kp-memclear+ 210)
  (+sdl-scancode-kp-memadd+ 211)
  (+sdl-scancode-kp-memsubtract+ 212)
  (+sdl-scancode-kp-memmultiply+ 213)
  (+sdl-scancode-kp-memdivide+ 214)
  (+sdl-scancode-kp-plusminus+ 215)
  (+sdl-scancode-kp-clear+ 216)
  (+sdl-scancode-kp-clearentry+ 217)
  (+sdl-scancode-kp-binary+ 218)
  (+sdl-scancode-kp-octal+ 219)
  (+sdl-scancode-kp-decimal+ 220)
  (+sdl-scancode-kp-hexadecimal+ 221)

  (+sdl-scancode-lctrl+ 224)
  (+sdl-scancode-lshift+ 225)
  (+sdl-scancode-lalt+ 226)
  (+sdl-scancode-lgui+ 227)
  (+sdl-scancode-rctrl+ 228)
  (+sdl-scancode-rshift+ 229)
  (+sdl-scancode-ralt+ 230)
  (+sdl-scancode-rgui+ 231)

  (+sdl-scancode-mode+ 257)


  (+sdl-scancode-audionext+ 258)
  (+sdl-scancode-audioprev+ 259)
  (+sdl-scancode-audiostop+ 260)
  (+sdl-scancode-audioplay+ 261)
  (+sdl-scancode-audiomute+ 262)
  (+sdl-scancode-mediaselect+ 263)
  (+sdl-scancode-www+ 264)
  (+sdl-scancode-mail+ 265)
  (+sdl-scancode-calculator+ 266)
  (+sdl-scancode-computer+ 267)
  (+sdl-scancode-ac-search+ 268)
  (+sdl-scancode-ac-home+ 269)
  (+sdl-scancode-ac-back+ 270)
  (+sdl-scancode-ac-forward+ 271)
  (+sdl-scancode-ac-stop+ 272)
  (+sdl-scancode-ac-refresh+ 273)
  (+sdl-scancode-ac-bookmarks+ 274)

  (+sdl-scancode-brightnessdown+ 275)
  (+sdl-scancode-brightnessup+ 276)
  (+sdl-scancode-displayswitch+ 277)
  (+sdl-scancode-kbdillumtoggle+ 278)
  (+sdl-scancode-kbdillumdown+ 279)
  (+sdl-scancode-kbdillumup+ 280)
  (+sdl-scancode-eject+ 281)
  (+sdl-scancode-sleep+ 282)

  (+sdl-scancode-app1+ 283)
  (+sdl-scancode-app2+ 284)

  (+sdl-scancode-audiorewind+ 285)
  (+sdl-scancode-audiofastforward+ 286)

  (+sdl-num-scancodes+ 512))
